url:
  base_url: http://120.26.10.118
#  base_url: https://api.codoon.com
log:
  log_name: log_
  file_log_level: info
  file_log_format: '[%(asctime)s] %(filename)s->%(funcName)s line:....'
  console_log_level: info
  console_log_format: '[%(asctime)s] %(filename)s->%(funcName)s line:....'
report:
  report_name: report_